const catalog=[
    {
        id:'obj1',
        name:'',
        img:'',
        price:'',
    },
    {
        id:'obj2',
        name:'',
        img:'',
        price:'',
    },
    {
        id:'obj3',
        clas:'detal',
        name:'',
        img:'',
        price:'',
    },
    {
        id:'obj4',
        clas:'detal',
        name:'',
        img:'',
        price:'',
    },
    {
        id:'obj5',
        clas:'detal',
        name:'',
        img:'',
        price:'',
    },
    {
        id:'obj6',
        name:'',
        img:'',
        price:'',
    }
];